language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.0
    - ANDROID_EMU_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
    - QEMU_AUDIO_DRV=none
    
android:
  components:
    #android sdk tools
    - tools
    - platform-tools
    
    #buildTools version
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    - sys-img-$ANDROID_ABI-google-apis-$ANDROID_EMU_API_LEVEL
    
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platform;android-$ANDROID_EMU_API_LEVEL"
  - yes | sdkmanager "platform;android-$ANDROID_API_LEVEL"
  
before_script:
  - chmod +x gradlew
  #Emulator instance
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_api/$ANDROID_ABI
  - emulator -avd test -no-window & 
  - android-wait-for-emulator
  - abd shell inut keyevent 82 &
  

#script:
#  - ./gradlew clean build
#  - ./gradlew test
